### ISSUE TITLE
Session show toggle off sign marks

### ISSUE THREAD

**Issue by leebrooks0** [alfredodeza/coveragepy.vim#9]
If you toggle off a session currently the buffer is removed but the signs are left behind.
It would be nice if there is an option or it defaults to removing the signs when closing the buffer

**Comment by alfredodeza** [comment]
The signs are left because `session` is independent to the signs. Signs are controlled by `show` (which one can toggle as well).
The problem with toggle commands is that it will just do the opposite of what exists. If I were to combine them it would mean that if the user had no signs but calls the session and then calls it again, the buffer disappears but the signs appear.

**Comment by alfredodeza** [comment]
Feel free to re-open if you think that maybe the docs should be a bit more explicit or if my explanation was not clear (or correct!)

**Comment by leebrooks0** [comment]
Thanks I see...
